### ISSUE TITLE
https://thehomelabber.com/guides/self-hosted-git-ci-cd/ - 403 Forbidden

### ISSUE THREAD

**Issue by jarbelix** [TheHomelabber/self-hosted-git-hello-world#1]
First of all, I would like to say that your tutorial is excellent.

Just one small detail in your README.md didn't work:
- The link https://thehomelabber.com/guides/self-hosted-git-ci-cd/ is giving "403 Forbidden".
- I think it would be interesting to change it to https://thehomelabber.com/series/self-hosted-git-with-gitea/

Thank you for sharing your knowledge

**Comment by jam3sn** [comment]
Hi @jarbelix, thanks for letting us know! I've updated that link to the guide series.

If you don't mind me asking, how did you come across the guide?

**Comment by jarbelix** [comment]
That was easy. All it took was a Google search with the right keywords:

self hosted git with gitea ci/cd

**Comment by jam3sn** [comment]
Amazing, good to see it paying off! Thanks for raising the issue with us :)
